module StackPlace
  unless const_defined?(:VERSION)
    VERSION = '1.0'
  end
end

# external core dependencies
require 'base64'
require 'json'
require 'open-uri'
require 'roar/representer/json'
require 'roar/representer/feature/hypermedia'
require 'httparty'
require 'active_model'

# internal libraries
require_relative 'stack_place/config'
require_relative 'stack_place/client/template_support'
require_relative 'stack_place/client/account_support'
require_relative 'stack_place/client/stack_support'
require_relative 'stack_place/client/identity_support'
require_relative 'stack_place/client/org_support'
require_relative 'stack_place/client/category_support'
require_relative 'stack_place/client/cloud_support'
require_relative 'stack_place/client/project_support'
require_relative 'stack_place/client/provisioning_support'
require_relative 'stack_place/client/report_support'
require_relative 'stack_place/client/news_event_support'

require_relative 'stack_place/http_client'
require_relative 'stack_place/error/errors'
require_relative 'stack_place/representer/error_representer'
require_relative 'stack_place/representer/link_representer'
require_relative 'stack_place/model/link'
require_relative 'stack_place/model/query'
require_relative 'stack_place/representer/query_representer'

require_relative 'stack_place/model/import_results'
require_relative 'stack_place/representer/import_results_representer'
require_relative 'stack_place/representer/report_representer'


require_relative 'stack_place/model/news_event'
require_relative 'stack_place/model/news_event_query'
require_relative 'stack_place/representer/news_event_representer'
require_relative 'stack_place/representer/update_news_event_representer'
require_relative 'stack_place/representer/news_event_query_representer'

require_relative 'stack_place/model/audit_log'
require_relative 'stack_place/model/cloud_resource'
require_relative 'stack_place/model/permission'
require_relative 'stack_place/model/cloud_account'
require_relative 'stack_place/model/cloud_mapping'
require_relative 'stack_place/model/price'
require_relative 'stack_place/representer/audit_log_representer'
require_relative 'stack_place/representer/cloud_resource_representer'
require_relative 'stack_place/representer/permission_representer'
require_relative 'stack_place/representer/update_permission_representer'
require_relative 'stack_place/representer/cloud_account_representer'
require_relative 'stack_place/representer/update_cloud_account_representer'
require_relative 'stack_place/representer/cloud_mapping_representer'
require_relative 'stack_place/representer/update_cloud_mapping_representer'
require_relative 'stack_place/representer/price_representer'
require_relative 'stack_place/representer/update_price_representer'
require_relative 'stack_place/model/cloud_service'
require_relative 'stack_place/model/cloud'
require_relative 'stack_place/model/cloud_query'
require_relative 'stack_place/representer/cloud_service_representer'
require_relative 'stack_place/representer/update_cloud_service_representer'
require_relative 'stack_place/representer/cloud_representer'
require_relative 'stack_place/representer/update_cloud_representer'
require_relative 'stack_place/representer/cloud_query_representer'

require_relative 'stack_place/model/account'
require_relative 'stack_place/model/project_membership'
require_relative 'stack_place/representer/project_membership_representer'
require_relative 'stack_place/representer/account_subscription_representer'
require_relative 'stack_place/model/account_subscription'
require_relative 'stack_place/representer/account_representer'
require_relative 'stack_place/representer/update_account_representer'
require_relative 'stack_place/representer/account_summary_representer'

require_relative 'stack_place/model/member'
require_relative 'stack_place/representer/member_representer'
require_relative 'stack_place/representer/update_member_representer'

require_relative 'stack_place/model/variant'
require_relative 'stack_place/representer/update_variant_representer'
require_relative 'stack_place/representer/variant_representer'

require_relative 'stack_place/model/environment'
require_relative 'stack_place/representer/environment_representer'
require_relative 'stack_place/representer/update_environment_representer'

require_relative 'stack_place/model/embedded_project'
require_relative 'stack_place/representer/embedded_project_representer'
require_relative 'stack_place/representer/update_embedded_project_representer'

require_relative 'stack_place/model/node_link'
require_relative 'stack_place/model/node'
require_relative 'stack_place/model/element'
require_relative 'stack_place/model/project_version'
require_relative 'stack_place/representer/element_representer'
require_relative 'stack_place/representer/node_link_representer'
require_relative 'stack_place/representer/node_representer'
require_relative 'stack_place/representer/project_version_representer'
require_relative 'stack_place/representer/node_representer'
require_relative 'stack_place/representer/update_node_representer'
require_relative 'stack_place/representer/node_link_representer'
require_relative 'stack_place/representer/element_representer'
require_relative 'stack_place/representer/update_element_representer'
require_relative 'stack_place/representer/elements_representer'
require_relative 'stack_place/representer/nodes_representer'

require_relative 'stack_place/model/provisioned_instance'
require_relative 'stack_place/model/provisioned_version'
require_relative 'stack_place/representer/update_provisioned_version_representer'
require_relative 'stack_place/representer/provisioned_instance_representer'
require_relative 'stack_place/representer/provisioned_version_representer'
require_relative 'stack_place/representer/provisioned_version_summary_representer'
require_relative 'stack_place/representer/update_provisioned_instance_representer'
require_relative 'stack_place/representer/provisioned_instances_representer'

require_relative 'stack_place/model/version'
require_relative 'stack_place/representer/version_representer'
require_relative 'stack_place/model/project'
require_relative 'stack_place/model/project_query'
require_relative 'stack_place/representer/project_representer'
require_relative 'stack_place/representer/update_project_representer'
require_relative 'stack_place/representer/project_query_representer'

require_relative 'stack_place/representer/template_representer'
require_relative 'stack_place/representer/import_template_representer'
require_relative 'stack_place/model/error'
require_relative 'stack_place/model/template'
require_relative 'stack_place/model/import_template'
require_relative 'stack_place/model/org'
require_relative 'stack_place/model/subscription'
require_relative 'stack_place/model/subscriber'
require_relative 'stack_place/representer/subscriber_representer'
require_relative 'stack_place/representer/add_subscriber_representer'
require_relative 'stack_place/representer/subscription_representer'
require_relative 'stack_place/representer/org_representer'
require_relative 'stack_place/representer/update_org_representer'
require_relative 'stack_place/representer/update_subscription_representer'

require_relative 'stack_place/model/category'
require_relative 'stack_place/model/stack'
require_relative 'stack_place/model/stack_query'
require_relative 'stack_place/model/create_stack'
require_relative 'stack_place/model/category_query'
require_relative 'stack_place/model/country'
require_relative 'stack_place/model/country_query'
require_relative 'stack_place/representer/category_representer'
require_relative 'stack_place/representer/update_category_representer'
require_relative 'stack_place/representer/category_summary_representer'
require_relative 'stack_place/representer/create_stack_representer'
require_relative 'stack_place/representer/stack_representer'
require_relative 'stack_place/representer/stack_query_representer'
require_relative 'stack_place/representer/category_query_representer'
require_relative 'stack_place/representer/country_representer'
require_relative 'stack_place/representer/country_query_representer'

